version: 2.1

executors:
  main-executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m

references:
  workspace_root: &workspace_root
                    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  android-deps:
    description: "Runs specialized Android cache step."
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-test/build.gradle" }}
      - run:
          name: "Download Android Dependencies"
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "core-test/build.gradle" }}

  prepare-job:
    description: "Pre-requisites that are required for all jobs."
    steps:
      - *attach_workspace
      - checkout
      - android-deps


jobs:
  unit-test-core:
    executor: main-executor
    steps:
      - prepare-job
      - run:
          name: Execute Core Unit Test Suite
          command: ./gradlew clean :core:jacocoTestReport
      - store_artifacts:
          path: core/build/reports/jacocoTestReport
          destination: coreTestReport
      - store_test_results:
          path: core/build/reports/jacocoTestReport

  unit-test-core-test:
    executor: main-executor
    steps:
      - prepare-job
      - run:
          name: Execute Core Test Unit Test Suite
          command: ./gradlew clean :core-test:jacocoTestReport
      - store_artifacts:
          path: core-test/build/reports/jacocoTestReport
          destination: coreTestTestReport
      - store_test_results:
          path: core-test/build/reports/jacocoTestReport

  detekt:
    executor: main-executor
    steps:
      - prepare-job
      - run:
          name: Execute Detekt For All Modules
          command: ./gradlew clean detekt

  lint:
    executor: main-executor
    steps:
      - prepare-job
      - run:
          name: Execute Lint For All Modules
          ./gradlew clean lint

workflows:
  version: 2
  verify_for_master:
    jobs:
      - detekt
      - lint
      - unit-test-core:
          requires:
            - detekt
            - lint
      - unit-test-core-test:
          requires:
            - detekt
            - lint